version: 1.0.{build}
branches:
  only:
  - master
configuration: Debug
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: Comentality.sln
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
    api_key:
      secure: hwJE79+GNbjQhL/4kz51wn1ZqkHgFWQtLf7s/JZENk8PtVkXjJ869jt57bH6iDHV
  skip_symbols: false
  artifact: /.*\.nupkg/
